spring:
  profiles:
    active: dev # Устанавливаем профиль dev как активный
  datasource:
    url: jdbc:postgresql://localhost:5433/taskdata
    username: postgres
    password: 7890123456Upet
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

service:
  permissions:
    username: alex
    password: 9999
    roles:
      - admin
      - user
      - teacher